### PR TITLE
modals props is undefined

### PR DESCRIPTION
**Pull request by sorenjuul**
Mapping out the modals props in mapStateToProps meant that modals was undefined on openModal

### CODE REVIEW

**Comment by sebinsua** [comment]
Could you fix the tests?

I'll take a look at this over the weekend. 

I'm actually a little confused about the code currently.

What is the difference between destructuring `modal` from `ownProps` and then passing it through explicitly as I was doing in this code, and not-destructuring `modal` from `ownProps` and just passing the whole of `...ownProps` in as you are doing.

Logically they should be exactly the same.

**Comment by sorenjuul** [comment]
Found the issue https://github.com/reactjs/react-redux/blob/master/docs/api.md#the-arity-of-mapstatetoprops-and-mapdispatchtoprops-determines-whether-they-receive-ownprops

Having a default parameter for ownProps means that undefined is always the resolved value

**Comment by sorenjuul** [comment]
Do you think it makes sense?

**Comment by sorenjuul** [comment]
Hi Seb

Could you look into this. Our solution is very dependent on this module and currently we are in a bad state as the current version doesn't work.

Thanks

**Comment by sebinsua** [comment]
Hi.

This makes sense to me. I'll merge and release this evening.

**Comment by sebinsua** [comment]
@vybu @sorenjuul Published at [`react-redux-simple-modal@0.2.5`](https://www.npmjs.com/package/react-redux-simple-modal)!

Sorry about that.

**Pull request merged**
